version: '3'
services:
  web:
    image: nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - 80:80
    restart: always
    depends_on:
      - php
      - db
  php:
    build: ./docker
    restart: always
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - .:/var/www/html
  composer:
    image: composer
    volumes:
      - .:/app
    command: install
  db:
    image: postgres:10.1
    restart: always
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/:/docker-entrypoint-initdb.d/
